### PR TITLE
Cleared buffer before new transition.

### PR DESCRIPTION
**Pull request by shubham14596**
Reset CurrentScreenFBO and nextScreenFBO on each new transition at the start of transition with the help of transitionStart flag.

### CODE REVIEW

**Comment by intrigus** [comment]
Could you explain why this change is necessary and what problem this solves?

**Comment by shubham14596** [comment]
Screenshot_2020-07-17-15-48-17-336_com patchnhack quotes
Artifacts seen during transition on same background with alpha channel when tested with given Gdxtest Test.

**Comment by digital-thinking** [comment]
First thanks for your pull request, highly appreciated.
I am trying to reproduce the issue, can you tell me what images do you use and in which transition this happens? Is it only the alpha fading transition?

Does your Render method use?
Gdx.gl.glClearColor(0, 0, 0, 0);

I guess you should fix it with:
Gdx.gl.glClearColor(0, 0, 0, 1);

I also updated the wiki, seems like that's the issue behind the problem.

**Comment by shubham14596** [comment]
@digital-thinking Looks like, this line,
Gdx.gl.glClearColor(0, 0, 0, 1);
fixed the problem.
I am extremely sorry for being too quick to raise a PR. I didn't realise that colour_buffer is set wrong. My bad..
Thanks. ;P
Your library is awesome.

**Pull request closed without merging**
